// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: security.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command definitions for Bidirectional Streaming
type CommandType int32

const (
	CommandType_UNKNOWN      CommandType = 0
	CommandType_BLOCK_IP     CommandType = 1
	CommandType_UNBLOCK_IP   CommandType = 2
	CommandType_PATCH_CONFIG CommandType = 3
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "UNKNOWN",
		1: "BLOCK_IP",
		2: "UNBLOCK_IP",
		3: "PATCH_CONFIG",
	}
	CommandType_value = map[string]int32{
		"UNKNOWN":      0,
		"BLOCK_IP":     1,
		"UNBLOCK_IP":   2,
		"PATCH_CONFIG": 3,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_security_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_security_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{0}
}

// Heartbeat Request and Response
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	CpuLoad       float64                `protobuf:"fixed64,3,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	MemLoad       float64                `protobuf:"fixed64,4,opt,name=mem_load,json=memLoad,proto3" json:"mem_load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HeartbeatRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuLoad() float64 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *HeartbeatRequest) GetMemLoad() float64 {
	if x != nil {
		return x.MemLoad
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Alert Report Request and Response
type AlertReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SourceIp      string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	AssetInfo     string                 `protobuf:"bytes,4,opt,name=asset_info,json=assetInfo,proto3" json:"asset_info,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity      string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	SignatureName string                 `protobuf:"bytes,7,opt,name=signature_name,json=signatureName,proto3" json:"signature_name,omitempty"`
	DestIp        string                 `protobuf:"bytes,8,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertReportRequest) Reset() {
	*x = AlertReportRequest{}
	mi := &file_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertReportRequest) ProtoMessage() {}

func (x *AlertReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertReportRequest.ProtoReflect.Descriptor instead.
func (*AlertReportRequest) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{2}
}

func (x *AlertReportRequest) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *AlertReportRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *AlertReportRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AlertReportRequest) GetAssetInfo() string {
	if x != nil {
		return x.AssetInfo
	}
	return ""
}

func (x *AlertReportRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AlertReportRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertReportRequest) GetSignatureName() string {
	if x != nil {
		return x.SignatureName
	}
	return ""
}

func (x *AlertReportRequest) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

type AlertReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AlertId       string                 `protobuf:"bytes,3,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertReportResponse) Reset() {
	*x = AlertReportResponse{}
	mi := &file_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertReportResponse) ProtoMessage() {}

func (x *AlertReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertReportResponse.ProtoReflect.Descriptor instead.
func (*AlertReportResponse) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{3}
}

func (x *AlertReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AlertReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlertReportResponse) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

// Command sent from Master to Agent
type CommandMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type      CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=security.CommandType" json:"type,omitempty"`
	// For BLOCK_IP / UNBLOCK_IP
	TargetIp string `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	// For PATCH_CONFIG
	ConfigPath     string `protobuf:"bytes,4,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	MatchRegex     string `protobuf:"bytes,5,opt,name=match_regex,json=matchRegex,proto3" json:"match_regex,omitempty"`
	ReplaceContent string `protobuf:"bytes,6,opt,name=replace_content,json=replaceContent,proto3" json:"replace_content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	mi := &file_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{4}
}

func (x *CommandMessage) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandMessage) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_UNKNOWN
}

func (x *CommandMessage) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *CommandMessage) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *CommandMessage) GetMatchRegex() string {
	if x != nil {
		return x.MatchRegex
	}
	return ""
}

func (x *CommandMessage) GetReplaceContent() string {
	if x != nil {
		return x.ReplaceContent
	}
	return ""
}

// Command execution result sent from Agent to Master
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // 标识哪个 Agent 返回的结果
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_security_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_security_proto protoreflect.FileDescriptor

const file_security_proto_rawDesc = "" +
	"\n" +
	"\x0esecurity.proto\x12\bsecurity\"t\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x19\n" +
	"\bcpu_load\x18\x03 \x01(\x01R\acpuLoad\x12\x19\n" +
	"\bmem_load\x18\x04 \x01(\x01R\amemLoad\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf6\x01\n" +
	"\x12AlertReportRequest\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12\x1d\n" +
	"\n" +
	"asset_info\x18\x04 \x01(\tR\tassetInfo\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12%\n" +
	"\x0esignature_name\x18\a \x01(\tR\rsignatureName\x12\x17\n" +
	"\adest_ip\x18\b \x01(\tR\x06destIp\"d\n" +
	"\x13AlertReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\balert_id\x18\x03 \x01(\tR\aalertId\"\xe2\x01\n" +
	"\x0eCommandMessage\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.security.CommandTypeR\x04type\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vconfig_path\x18\x04 \x01(\tR\n" +
	"configPath\x12\x1f\n" +
	"\vmatch_regex\x18\x05 \x01(\tR\n" +
	"matchRegex\x12'\n" +
	"\x0freplace_content\x18\x06 \x01(\tR\x0ereplaceContent\"}\n" +
	"\rCommandResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*J\n" +
	"\vCommandType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bBLOCK_IP\x10\x01\x12\x0e\n" +
	"\n" +
	"UNBLOCK_IP\x10\x02\x12\x10\n" +
	"\fPATCH_CONFIG\x10\x032\xf5\x01\n" +
	"\x0fSecurityService\x12J\n" +
	"\rSendHeartbeat\x12\x1a.security.HeartbeatRequest\x1a\x1b.security.HeartbeatResponse\"\x00\x12L\n" +
	"\vReportAlert\x12\x1c.security.AlertReportRequest\x1a\x1d.security.AlertReportResponse\"\x00\x12H\n" +
	"\rCommandStream\x12\x17.security.CommandResult\x1a\x18.security.CommandMessage\"\x00(\x010\x01B)Z'security-response-system/internal/protob\x06proto3"

var (
	file_security_proto_rawDescOnce sync.Once
	file_security_proto_rawDescData []byte
)

func file_security_proto_rawDescGZIP() []byte {
	file_security_proto_rawDescOnce.Do(func() {
		file_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_proto_rawDesc), len(file_security_proto_rawDesc)))
	})
	return file_security_proto_rawDescData
}

var file_security_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_security_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_security_proto_goTypes = []any{
	(CommandType)(0),            // 0: security.CommandType
	(*HeartbeatRequest)(nil),    // 1: security.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 2: security.HeartbeatResponse
	(*AlertReportRequest)(nil),  // 3: security.AlertReportRequest
	(*AlertReportResponse)(nil), // 4: security.AlertReportResponse
	(*CommandMessage)(nil),      // 5: security.CommandMessage
	(*CommandResult)(nil),       // 6: security.CommandResult
}
var file_security_proto_depIdxs = []int32{
	0, // 0: security.CommandMessage.type:type_name -> security.CommandType
	1, // 1: security.SecurityService.SendHeartbeat:input_type -> security.HeartbeatRequest
	3, // 2: security.SecurityService.ReportAlert:input_type -> security.AlertReportRequest
	6, // 3: security.SecurityService.CommandStream:input_type -> security.CommandResult
	2, // 4: security.SecurityService.SendHeartbeat:output_type -> security.HeartbeatResponse
	4, // 5: security.SecurityService.ReportAlert:output_type -> security.AlertReportResponse
	5, // 6: security.SecurityService.CommandStream:output_type -> security.CommandMessage
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_security_proto_init() }
func file_security_proto_init() {
	if File_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_proto_rawDesc), len(file_security_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_proto_goTypes,
		DependencyIndexes: file_security_proto_depIdxs,
		EnumInfos:         file_security_proto_enumTypes,
		MessageInfos:      file_security_proto_msgTypes,
	}.Build()
	File_security_proto = out.File
	file_security_proto_goTypes = nil
	file_security_proto_depIdxs = nil
}
